AWSTemplateFormatVersion: "2010-09-09"
Description: VueltaCam AWS stack with nested stacks for each resource.

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  
  LowercaseStackName:
    Type: String

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Resources:
  DynamoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested/dynamoDB.yaml
      Parameters:
        ParentStackName: !Select [0, !Split ["-", !Ref "AWS::StackName"]]  # foo
        Environment: !Ref Environment

  IoTRulesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [
      DynamoStack,
      S3Stack
    ]
    Properties:
      TemplateURL: nested/IoTRules.yaml
      Parameters:
        ParentStackName: !Select [0, !Split ["-", !Ref "AWS::StackName"]]  # foo
        Environment: !Ref Environment
        DynamoTableName: !GetAtt DynamoStack.Outputs.TableName
        DynamoTableArn: !GetAtt DynamoStack.Outputs.TableArn
        DynamoRoleArn: !GetAtt DynamoStack.Outputs.IoTRuleRoleArn
        UploadBucketName: !GetAtt S3Stack.Outputs.CameraDataBucketName
  
  IoTCoreStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested/IoTCore.yaml
      Parameters:
        ParentStackName: !Select [0, !Split ["-", !Ref "AWS::StackName"]]  # foo
        Environment: !Ref Environment
  
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested/S3.yaml
      Parameters:
        ParentStackName: !Select [0, !Split ["-", !Ref "AWS::StackName"]]  # Foo
        LowercaseStackName: !Ref LowercaseStackName                        # foo
        Environment: !Ref Environment
  
  AppSyncStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoStack
    Properties:
      TemplateURL: nested/appSync.yaml
      Parameters:
        ParentStackName: !Select [0, !Split ["-", !Ref "AWS::StackName"]]  # foo
        Environment: !Ref Environment
        DynamoTableName: !GetAtt DynamoStack.Outputs.TableName
        DynamoTableArn: !GetAtt DynamoStack.Outputs.TableArn
        AuthType: API_KEY # optional (AWS_IAM or API_KEY)
        AppSyncManagerRoleName: !If [IsProd, "yx-deployer-prod", "yx-deployer-devtest"]


Outputs:
  RootStackName:
    Value: !Ref AWS::StackName
  DynamoTableName:
    Value: !GetAtt DynamoStack.Outputs.TableName
  IotRuleRoleArn:
    Value: !GetAtt DynamoStack.Outputs.IoTRuleRoleArn
  UpdateOngoingRecordingLambdaArn:
    Value: !GetAtt IoTRulesStack.Outputs.UpdateOngoingRecordingLambdaArn
